# Generated by Django 4.0.2 on 2022-02-21 09:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0002_playlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='embeddedsound',
            name='url',
            field=models.URLField(validators=[django.core.validators.RegexValidator(regex='/^((?:https?:)?\\/\\/)?((?:www|m)\\.)?(?:youtube\\.com|youtu.be)(\\/(?:[\\w-]+\\?v=|embed\\/|v\\/)?)([\\w-]+)(\\S+)?$/')]),
        ),
    ]
